name: Build APK with Buildozer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git zip unzip openjdk-17-jdk python3-pip
        pip install --upgrade pip
        pip install buildozer cython

    - name: Init buildozer and spec file
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
          sed -i 's/^requirements = .*/requirements = python3,kivy/' buildozer.spec
          sed -i 's/^package.name = .*/package.name = ChickenRoad/' buildozer.spec
          sed -i 's/^package.domain = .*/package.domain = org.chicken.road/' buildozer.spec
        fi

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: chicken-road-apk
        path: bin/*.apk
